services:
  - type: web
    name: lexforge-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install -r backend/requirements.txt && python backend/nltk_setup.py
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: ORIGIN
        value: https://lexforge.vercel.app
    cors:
      allowOrigins:
        - https://lexforge.vercel.app
    disks:
      - name: data-disk
        mountPath: /opt/render/project/src/backend/data
        sizeGB: 1
      - name: tmp-disk
        mountPath: /opt/render/project/src/backend/tmp
        sizeGB: 1
